### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by adminy** [warren-bank/node-rtsp-relay#2]
```bash
rtsp-relay --producer-port 5554 --client-port 8554 --log=4
```

then I tried connecting a producer:
```bash
# on the macbook:

ffmpeg -y -r 30 -f avfoundation -i "0" \
  -c:v libx264 -s 1280x720 -pix_fmt yuv420p \
  -c:a aac -b:a 128k -ar 44100 \
  -f rtsp -muxdelay 0.1 rtsp://0.0.0.0:5554/

# or on the pi
libcamera-vid -t 0 -o - | ffmpeg \
             -re -i - -hide_banner -y -loglevel error \
             -c:v copy  \
             -c:a aac -b:a 128k -ar 44100    \
             -max_muxing_queue_size 1024 \
             -f rtsp rtsp://0.0.0.0:5554/

# Logs

[rtsp @ 0x12c828400] method ANNOUNCE failed: 503 Service Unavailable
Could not write header for output file #0 (incorrect codec parameters ?): Server returned 5XX Server Error reply
Error initializing output stream 0:0 -- 
```

any parameter I am missing?

**Comment by warren-bank** [comment]
1. change the format of input params for the relay from `--a=b` to `--a 'b'`
2. `ffmpeg -i '0'`
   * is this a valid input stream?
   * _update_: [these examples](https://ffmpeg.org/ffmpeg-all.html#Examples-22) explain its meaning.. all good
     - though it might be worth trying `-i '0:0'` instead

**Comment by warren-bank** [comment]
oh.. and aren't you're specifying output format `-f xxx` twice?
* 1st for `avfoundation`
* 2nd for `rtsp`.. which is what it needs to be
  - _update_: [these examples](https://ffmpeg.org/ffmpeg-all.html#Examples-31) do the same.. all good
    * looks like you can specify both input format and output format

**Comment by warren-bank** [comment]
and.. correct me if I'm wrong..
* these errors are coming purely from `ffmpeg`
* you haven't gotten to the point yet where the relay is being used by any consumer..<br>so it's just sitting there idle.. same as if it hadn't been started yet

**Comment by warren-bank** [comment]
sorry, I haven't looked at this in ages..

referring back to my [original example](https://github.com/warren-bank/node-rtsp-relay/tree/master/tests/01-ffmpeg)..
I see that it uses the [ffmpeg options](https://github.com/warren-bank/node-rtsp-relay/blob/master/tests/01-ffmpeg/2-rtsp-producer.bat#L25-L29):
```bash
  -c:a copy -c:v mpeg1video -q 15 -f rtsp -rtsp_transport udp -muxdelay 0.1 rtsp://127.0.0.1:5554/stream1
```

* if the relay is listening at its producer port
* then ffmpeg is probably trying to connect and publish to it
  - so.. `0.0.0.0` wouldn't make any sense
  - it looks like the stream should be given a label (ex: `/stream1`)
    * I don't remember if this is optional, but probably not..<br>since it allows the consumer to select a unique stream (by name)

**Comment by warren-bank** [comment]
maybe try?
```bash
ffmpeg -f avfoundation -i '0:0' -c:a copy -c:v mpeg1video -r 30 -q 15 -f rtsp -rtsp_transport udp -muxdelay 0.1 rtsp://127.0.0.1:5554/stream1
```

just as an fyi, even though this tweak won't be relevent to you..
I'm currently on Windows
* `ffmpeg` says: _Unknown input format: 'avfoundation'_
* `ffmpeg` works when I modify the above command to use [`DirectShow`](https://trac.ffmpeg.org/wiki/DirectShow) for webcam input:
  ```bash
    ffmpeg -f dshow -i video="HP HD Webcam" -c:a copy -c:v mpeg1video -r 30 -q 15 -f rtsp -rtsp_transport udp -muxdelay 0.1 rtsp://127.0.0.1:5554/stream1
  ```

**Comment by adminy** [comment]
I've updated the command:
```bash
rtsp-relay --producer-port 5554 --client-port 8554 --log 4 &

libcamera-vid -t 0 -o - | ffmpeg \
          -re -i - -hide_banner -y -loglevel error \
          -c:v copy \
           -c:a aac -b:a 128k -ar 44100 \
           -max_muxing_queue_size 1024  \
            -f rtsp -rtsp_transport udp -muxdelay 0.1   \
          rtsp://127.0.0.1:5554/stream1
```

now the producer is fine, but when I invoke vlc as a client, I get the following error at the end when I connect:

```log
  rtsp-relay:1:ProducerServer RTSP producer server is running on port: 5554 +0ms
  rtsp-relay:1:ConsumerServer RTSP consumer server is running on port: 8554 +4ms
  rtsp-server new socket connection +19s
  rtsp-stream decoding chunk 'OPTIONS rtsp://127.0.0.1:5554/stream1 RTSP/1.0\r\n' +
  'CSeq: 1\r\n' +
  'User-Agent: Lavf58.45.100\r\n' +
  '\r\n' +21ms
  rtsp-stream start of header +2ms
  rtsp-stream end of header +3ms
  rtsp-server OPTIONS rtsp://127.0.0.1:5554/stream1 { cseq: '1', 'user-agent': 'Lavf58.45.100' } +6ms
  rtsp-relay:2:ProducerServer Options request from ::ffff:127.0.0.1 with headers { cseq: '1', 'user-agent': 'Lavf58.45.100' } +12ms
  rtsp-stream start-line sent RTSP/1.0 200 OK +8ms
  rtsp-stream headers sent {
  CSeq: '1',
  Date: 'Sun, 04 Jun 2023 05:59:51 GMT',
  OPTIONS: 'DESCRIBE SETUP ANNOUNCE RECORD'
} +5ms
  rtsp-stream decoding chunk 'ANNOUNCE rtsp://127.0.0.1:5554/stream1 RTSP/1.0\r\n' +
  'Content-Type: application/sdp\r\n' +
  'CSeq: 2\r\n' +
  'User-Agent: Lavf58.45.100\r\n' +
  'Content-Length: 304\r\n' +
  '\r\n' +
  'v=0\r\n' +
  'o=- 0 0 IN IP4 127.0.0.1\r\n' +
  's=No Name\r\n' +
  'c=IN IP4 127.0.0.1\r\n' +
  't=0 0\r\n' +
  'a=tool:libavformat 58.45.100\r\n' +
  'm=video 0 RTP/AVP 96\r\n' +
  'a=rtpmap:96 H264/90000\r\n' +
  'a=fmtp:96 packetization-mode=1; sprop-parameter-sets=J2QAKKwrQFAe0IAAAAMAgAAAHnJQABMSwAAvrze9wDxImoA=,KO4fLAA=; profile-level-id=640028\r\n' +
  'a=control:streamid=0\r\n' +7ms
  rtsp-stream start of header +2ms
  rtsp-stream end of header +1ms
  rtsp-server ANNOUNCE rtsp://127.0.0.1:5554/stream1 {
  'content-type': 'application/sdp',
  cseq: '2',
  'user-agent': 'Lavf58.45.100',
  'content-length': '304'
} +3ms
  rtsp-relay:2:ProducerServer ::ffff:127.0.0.1:47884 - Announce request with headers { 'content-type': 'application/sdp', cseq: '2', 'user-agent': 'Lavf58.45.100', 'content-length': '304' } +3ms
  rtsp-stream decoding chunk 'v=0\r\n' +
  'o=- 0 0 IN IP4 127.0.0.1\r\n' +
  's=No Name\r\n' +
  'c=IN IP4 127.0.0.1\r\n' +
  't=0 0\r\n' +
  'a=tool:libavformat 58.45.100\r\n' +
  'm=video 0 RTP/AVP 96\r\n' +
  'a=rtpmap:96 H264/90000\r\n' +
  'a=fmtp:96 packetization-mode=1; sprop-parameter-sets=J2QAKKwrQFAe0IAAAAMAgAAAHnJQABMSwAAvrze9wDxImoA=,KO4fLAA=; profile-level-id=640028\r\n' +
  'a=control:streamid=0\r\n' +3ms
  rtsp-stream start of body +1ms
  rtsp-stream end of body +4ms
  rtsp-relay:2:Mounts Adding mount with path rtsp://127.0.0.1:5554/stream1 and SDP 'v=0\r\n' +
  rtsp-relay:2:Mounts   'o=- 0 0 IN IP4 127.0.0.1\r\n' +
  rtsp-relay:2:Mounts   's=No Name\r\n' +
  rtsp-relay:2:Mounts   'c=IN IP4 127.0.0.1\r\n' +
  rtsp-relay:2:Mounts   't=0 0\r\n' +
  rtsp-relay:2:Mounts   'a=tool:libavformat 58.45.100\r\n' +
  rtsp-relay:2:Mounts   'm=video 0 RTP/AVP 96\r\n' +
  rtsp-relay:2:Mounts   'a=rtpmap:96 H264/90000\r\n' +
  rtsp-relay:2:Mounts   'a=fmtp:96 packetization-mode=1; sprop-parameter-sets=J2QAKKwrQFAe0IAAAAMAgAAAHnJQABMSwAAvrze9wDxImoA=,KO4fLAA=; profile-level-id=640028\r\n' +
  rtsp-relay:2:Mounts   'a=control:streamid=0\r\n' +6ms
  rtsp-relay:1:Mount Set up mount at path /stream1 +2ms
  rtsp-relay:2:ProducerServer ::ffff:127.0.0.1:47884 - Set session to 1515452231212517523917257172143250250226152 +1ms
  rtsp-stream start-line sent RTSP/1.0 200 OK +1ms
  rtsp-stream headers sent {
  CSeq: '2',
  Date: 'Sun, 04 Jun 2023 05:59:51 GMT',
  Session: '1515452231212517523917257172143250250226152;timeout=30'
} +1ms
  rtsp-stream decoding chunk 'SETUP rtsp://127.0.0.1:5554/stream1/streamid=0 RTSP/1.0\r\n' +
  'Transport: RTP/AVP/UDP;unicast;client_port=22590-22591;mode=record\r\n' +
  'CSeq: 3\r\n' +
  'User-Agent: Lavf58.45.100\r\n' +
  'Session: 1515452231212517523917257172143250250226152\r\n' +
  '\r\n' +44ms
  rtsp-stream start of header +1ms
  rtsp-stream end of header +0ms
  rtsp-server SETUP rtsp://127.0.0.1:5554/stream1/streamid=0 {
  transport: 'RTP/AVP/UDP;unicast;client_port=22590-22591;mode=record',
  cseq: '3',
  'user-agent': 'Lavf58.45.100',
  session: '1515452231212517523917257172143250250226152'
} +1ms
  rtsp-relay:2:Mounts 4999 rtp ports remaining +3ms
  rtsp-relay:1:Mount Setting up stream 0 on path /stream1 +0ms
  rtsp-stream start-line sent RTSP/1.0 200 OK +1ms
  rtsp-stream headers sent {
  CSeq: '3',
  Date: 'Sun, 04 Jun 2023 05:59:51 GMT',
  Transport: 'RTP/AVP/UDP;unicast;client_port=22590-22591;mode=record;server_port=10000-10001'
} +1ms
  rtsp-stream decoding chunk 'RECORD rtsp://127.0.0.1:5554/stream1 RTSP/1.0\r\n' +
  'Range: npt=0.000-\r\n' +
  'CSeq: 4\r\n' +
  'User-Agent: Lavf58.45.100\r\n' +
  'Session: 1515452231212517523917257172143250250226152\r\n' +
  '\r\n' +40ms
  rtsp-stream start of header +1ms
  rtsp-stream end of header +0ms
  rtsp-server RECORD rtsp://127.0.0.1:5554/stream1 {
  range: 'npt=0.000-',
  cseq: '4',
  'user-agent': 'Lavf58.45.100',
  session: '1515452231212517523917257172143250250226152'
} +1ms
  rtsp-relay:2:RtpUdp Opened RTP listener for stream 0 on path /stream1 +9ms
  rtsp-relay:2:RtpUdp Opened RTCP listener for stream 0 on path /stream1 +2ms
  rtsp-stream start-line sent RTSP/1.0 200 OK +1ms
  rtsp-stream headers sent { CSeq: '4', Date: 'Sun, 04 Jun 2023 05:59:51 GMT' } +1ms
  rtsp-server new socket connection +21s
  rtsp-stream decoding chunk 'OPTIONS rtsp://192.168.1.103:8554/stream1 RTSP/1.0\r\n' +
  'CSeq: 2\r\n' +
  'User-Agent: LibVLC/3.0.19 (LIVE555 Streaming Media v2016.10.21)\r\n' +
  '\r\n' +9ms
  rtsp-stream start of header +1ms
  rtsp-stream end of header +0ms
  rtsp-server OPTIONS rtsp://192.168.1.103:8554/stream1 {
  cseq: '2',
  'user-agent': 'LibVLC/3.0.19 (LIVE555 Streaming Media v2016.10.21)'
} +2ms
  rtsp-relay:2:ConsumerServer ::ffff:192.168.1.102:55057 request: OPTIONS +1ms
  rtsp-stream start-line sent RTSP/1.0 200 OK +3ms
  rtsp-stream headers sent {
  CSeq: '2',
  Date: 'Sun, 04 Jun 2023 06:00:12 GMT',
  OPTIONS: 'DESCRIBE SETUP PLAY STOP'
} +4ms
  rtsp-stream decoding chunk 'DESCRIBE rtsp://192.168.1.103:8554/stream1 RTSP/1.0\r\n' +
  'CSeq: 3\r\n' +
  'User-Agent: LibVLC/3.0.19 (LIVE555 Streaming Media v2016.10.21)\r\n' +
  'Accept: application/sdp\r\n' +
  '\r\n' +9ms
  rtsp-stream start of header +0ms
  rtsp-stream end of header +0ms
  rtsp-server DESCRIBE rtsp://192.168.1.103:8554/stream1 {
  cseq: '3',
  'user-agent': 'LibVLC/3.0.19 (LIVE555 Streaming Media v2016.10.21)',
  accept: 'application/sdp'
} +3ms
  rtsp-relay:2:ConsumerServer ::ffff:192.168.1.102:55057 request: DESCRIBE +1ms
  rtsp-stream start-line sent RTSP/1.0 200 OK +6ms
  rtsp-stream headers sent {
  CSeq: '3',
  Date: 'Sun, 04 Jun 2023 06:00:12 GMT',
  'Content-Type': 'application/sdp',
  'Content-Length': 304
} +1ms
  rtsp-stream decoding chunk 'SETUP rtsp://192.168.1.103:8554/stream1/streamid=0 RTSP/1.0\r\n' +
  'CSeq: 4\r\n' +
  'User-Agent: LibVLC/3.0.19 (LIVE555 Streaming Media v2016.10.21)\r\n' +
  'Transport: RTP/AVP/TCP;unicast;interleaved=0-1\r\n' +
  '\r\n' +73ms
  rtsp-stream start of header +1ms
  rtsp-stream end of header +0ms
  rtsp-server SETUP rtsp://192.168.1.103:8554/stream1/streamid=0 {
  cseq: '4',
  'user-agent': 'LibVLC/3.0.19 (LIVE555 Streaming Media v2016.10.21)',
  transport: 'RTP/AVP/TCP;unicast;interleaved=0-1'
} +1ms
  rtsp-relay:2:ConsumerServer ::ffff:192.168.1.102:55057 request: SETUP +1ms
  rtsp-relay:2:ConsumerServer ::ffff:192.168.1.102:55057 - we dont support tcp, sending 504: 'rtsp://192.168.1.103:8554/stream1/streamid=0' +1ms
  rtsp-stream start-line sent RTSP/1.0 504 Gateway Time-out +1ms
  rtsp-stream headers sent { CSeq: '4', Date: 'Sun, 04 Jun 2023 06:00:12 GMT' } +1ms
  rtsp-server socket connection ended +20ms
  rtsp-server socket connection closed +9ms
  rtsp-server new socket connection +66ms
  rtsp-stream decoding chunk 'OPTIONS rtsp://192.168.1.103:8554/stream1 RTSP/1.0\r\n' +
  'CSeq: 2\r\n' +
  'User-Agent: LibVLC/3.0.19 (LIVE555 Streaming Media v2016.10.21)\r\n' +
  '\r\n' +6ms
  rtsp-stream start of header +2ms
  rtsp-stream end of header +0ms
  rtsp-server OPTIONS rtsp://192.168.1.103:8554/stream1 {
  cseq: '2',
  'user-agent': 'LibVLC/3.0.19 (LIVE555 Streaming Media v2016.10.21)'
} +3ms
  rtsp-relay:2:ConsumerServer ::ffff:192.168.1.102:55058 request: OPTIONS +3ms
  rtsp-stream start-line sent RTSP/1.0 200 OK +1ms
  rtsp-stream headers sent {
  CSeq: '2',
  Date: 'Sun, 04 Jun 2023 06:00:13 GMT',
  OPTIONS: 'DESCRIBE SETUP PLAY STOP'
} +1ms
  rtsp-stream decoding chunk 'DESCRIBE rtsp://192.168.1.103:8554/stream1 RTSP/1.0\r\n' +
  'CSeq: 3\r\n' +
  'User-Agent: LibVLC/3.0.19 (LIVE555 Streaming Media v2016.10.21)\r\n' +
  'Accept: application/sdp\r\n' +
  '\r\n' +85ms
  rtsp-stream start of header +0ms
  rtsp-stream end of header +0ms
  rtsp-server DESCRIBE rtsp://192.168.1.103:8554/stream1 {
  cseq: '3',
  'user-agent': 'LibVLC/3.0.19 (LIVE555 Streaming Media v2016.10.21)',
  accept: 'application/sdp'
} +1ms
  rtsp-relay:2:ConsumerServer ::ffff:192.168.1.102:55058 request: DESCRIBE +2ms
  rtsp-stream start-line sent RTSP/1.0 200 OK +3ms
  rtsp-stream headers sent {
  CSeq: '3',
  Date: 'Sun, 04 Jun 2023 06:00:13 GMT',
  'Content-Type': 'application/sdp',
  'Content-Length': 304
} +2ms
  rtsp-stream decoding chunk 'SETUP rtsp://192.168.1.103:8554/stream1/streamid=0 RTSP/1.0\r\n' +
  'CSeq: 4\r\n' +
  'User-Agent: LibVLC/3.0.19 (LIVE555 Streaming Media v2016.10.21)\r\n' +
  'Transport: RTP/AVP/TCP;unicast;interleaved=0-1\r\n' +
  '\r\n' +95ms
  rtsp-stream start of header +1ms
  rtsp-stream end of header +0ms
  rtsp-server SETUP rtsp://192.168.1.103:8554/stream1/streamid=0 {
  cseq: '4',
  'user-agent': 'LibVLC/3.0.19 (LIVE555 Streaming Media v2016.10.21)',
  transport: 'RTP/AVP/TCP;unicast;interleaved=0-1'
} +2ms
  rtsp-relay:2:ConsumerServer ::ffff:192.168.1.102:55058 request: SETUP +2ms
  rtsp-relay:2:ConsumerServer ::ffff:192.168.1.102:55058 - we dont support tcp, sending 504: 'rtsp://192.168.1.103:8554/stream1/streamid=0' +2ms
  rtsp-stream start-line sent RTSP/1.0 504 Gateway Time-out +1ms
  rtsp-stream headers sent { CSeq: '4', Date: 'Sun, 04 Jun 2023 06:00:13 GMT' } +1ms
  rtsp-server socket connection ended +307ms
  rtsp-server socket connection closed +3ms
  rtsp-server new socket connection +3ms
  rtsp-stream decoding chunk 'OPTIONS rtsp://192.168.1.103:8554/stream1 RTSP/1.0\r\n' +
  'CSeq: 2\r\n' +
  'User-Agent: LibVLC/3.0.19 (LIVE555 Streaming Media v2016.10.21)\r\n' +
  '\r\n' +4ms
  rtsp-stream start of header +1ms
  rtsp-stream end of header +0ms
  rtsp-server OPTIONS rtsp://192.168.1.103:8554/stream1 {
  cseq: '2',
  'user-agent': 'LibVLC/3.0.19 (LIVE555 Streaming Media v2016.10.21)'
} +2ms
  rtsp-relay:2:ConsumerServer ::ffff:192.168.1.102:55059 request: OPTIONS +4ms
  rtsp-stream start-line sent RTSP/1.0 200 OK +1ms
  rtsp-stream headers sent {
  CSeq: '2',
  Date: 'Sun, 04 Jun 2023 06:00:13 GMT',
  OPTIONS: 'DESCRIBE SETUP PLAY STOP'
} +1ms
  rtsp-stream decoding chunk 'DESCRIBE rtsp://192.168.1.103:8554/stream1 RTSP/1.0\r\n' +
  'CSeq: 3\r\n' +
  'User-Agent: LibVLC/3.0.19 (LIVE555 Streaming Media v2016.10.21)\r\n' +
  'Accept: application/sdp\r\n' +
  '\r\n' +6ms
  rtsp-stream start of header +1ms
  rtsp-stream end of header +0ms
  rtsp-server DESCRIBE rtsp://192.168.1.103:8554/stream1 {
  cseq: '3',
  'user-agent': 'LibVLC/3.0.19 (LIVE555 Streaming Media v2016.10.21)',
  accept: 'application/sdp'
} +2ms
  rtsp-relay:2:ConsumerServer ::ffff:192.168.1.102:55059 request: DESCRIBE +1ms
  rtsp-stream start-line sent RTSP/1.0 200 OK +3ms
  rtsp-stream headers sent {
  CSeq: '3',
  Date: 'Sun, 04 Jun 2023 06:00:13 GMT',
  'Content-Type': 'application/sdp',
  'Content-Length': 304
} +3ms
  rtsp-stream decoding chunk 'SETUP rtsp://192.168.1.103:8554/stream1/streamid=0 RTSP/1.0\r\n' +
  'CSeq: 4\r\n' +
  'User-Agent: LibVLC/3.0.19 (LIVE555 Streaming Media v2016.10.21)\r\n' +
  'Transport: RTP/AVP/TCP;unicast;interleaved=0-1\r\n' +
  '\r\n' +66ms
  rtsp-stream start of header +0ms
  rtsp-stream end of header +1ms
  rtsp-server SETUP rtsp://192.168.1.103:8554/stream1/streamid=0 {
  cseq: '4',
  'user-agent': 'LibVLC/3.0.19 (LIVE555 Streaming Media v2016.10.21)',
  transport: 'RTP/AVP/TCP;unicast;interleaved=0-1'
} +2ms
  rtsp-relay:2:ConsumerServer ::ffff:192.168.1.102:55059 request: SETUP +1ms
  rtsp-relay:2:ConsumerServer ::ffff:192.168.1.102:55059 - we dont support tcp, sending 504: 'rtsp://192.168.1.103:8554/stream1/streamid=0' +1ms
  rtsp-stream start-line sent RTSP/1.0 504 Gateway Time-out +1ms
  rtsp-stream headers sent { CSeq: '4', Date: 'Sun, 04 Jun 2023 06:00:13 GMT' } +1ms
  rtsp-server socket connection ended +93ms
  rtsp-server socket connection closed +2ms
  rtsp-server new socket connection +3ms
  rtsp-stream decoding chunk 'SETUP rtsp://192.168.1.103:8554/stream1 RTSP/1.0\r\n' +
  'CSeq: 0\r\n' +
  'Transport: RTP/AVP;unicast;client_port=9376-9377\r\n' +
  '\r\n' +2ms
  rtsp-stream start of header +0ms
  rtsp-stream end of header +0ms
  rtsp-server SETUP rtsp://192.168.1.103:8554/stream1 { cseq: '0', transport: 'RTP/AVP;unicast;client_port=9376-9377' } +3ms
  rtsp-relay:2:ConsumerServer ::ffff:192.168.1.102:55060 request: SETUP +1ms
  rtsp-relay:2:ClientWrapper 379768602381916710514016413727211161204243 - constructed +3ms
  rtsp-relay:2:Mounts 4998 rtp ports remaining +3ms
  rtsp-relay:2:ClientWrapper 379768602381916710514016413727211161204243 new client 1671191802041531866791128171227231184111203162 +0ms
  rtsp-relay:2:ConsumerServer Error setting up client TypeError: Cannot read properties of undefined (reading 'mount')
    at Client.setup (/usr/lib/node_modules/@warren-bank/rtsp-relay/lib/rtsp-streaming-server/lib/Client.js:76:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConsumerServer.setupRequest (/usr/lib/node_modules/@warren-bank/rtsp-relay/lib/rtsp-streaming-server/lib/ConsumerServer.js:136:7) +4ms
  rtsp-stream start-line sent RTSP/1.0 500 Internal Server Error +5ms
  rtsp-stream headers sent { CSeq: '0', Date: 'Sun, 04 Jun 2023 06:00:13 GMT' } +1ms
  rtsp-server socket connection ended +76ms
  rtsp-server socket connection closed +2ms
  rtsp-server new socket connection +3ms
  rtsp-stream decoding chunk 'SETUP rtsp://192.168.1.103:8554/stream1 RTSP/1.0\r\n' +
  'CSeq: 0\r\n' +
  'Transport: RTP/AVP;unicast;client_port=9356-9357\r\n' +
  '\r\n' +2ms
  rtsp-stream start of header +1ms
  rtsp-stream end of header +2ms
  rtsp-server SETUP rtsp://192.168.1.103:8554/stream1 { cseq: '0', transport: 'RTP/AVP;unicast;client_port=9356-9357' } +2ms
  rtsp-relay:2:ConsumerServer ::ffff:192.168.1.102:55061 request: SETUP +1ms
  rtsp-relay:2:ClientWrapper 552553913922529711041441212491581303423538 - constructed +2ms
  rtsp-relay:2:Mounts 4997 rtp ports remaining +2ms
  rtsp-relay:2:ClientWrapper 552553913922529711041441212491581303423538 new client 215159217174135837617017812220818935127245198 +0ms
  rtsp-relay:2:ConsumerServer Error setting up client TypeError: Cannot read properties of undefined (reading 'mount')
    at Client.setup (/usr/lib/node_modules/@warren-bank/rtsp-relay/lib/rtsp-streaming-server/lib/Client.js:76:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConsumerServer.setupRequest (/usr/lib/node_modules/@warren-bank/rtsp-relay/lib/rtsp-streaming-server/lib/ConsumerServer.js:136:7) +2ms
  rtsp-stream start-line sent RTSP/1.0 500 Internal Server Error +2ms
  rtsp-stream headers sent { CSeq: '0', Date: 'Sun, 04 Jun 2023 06:00:13 GMT' } +2ms
  rtsp-server socket connection ended +79ms
  rtsp-server socket connection closed +1ms
  rtsp-server new socket connection +5ms
  rtsp-stream decoding chunk 'SETUP rtsp://192.168.1.103:8554/stream1 RTSP/1.0\r\n' +
  'CSeq: 0\r\n' +
  'Transport: RTP/AVP;unicast;client_port=9334-9335\r\n' +
  '\r\n' +3ms
  rtsp-stream start of header +1ms
  rtsp-stream end of header +0ms
  rtsp-server SETUP rtsp://192.168.1.103:8554/stream1 { cseq: '0', transport: 'RTP/AVP;unicast;client_port=9334-9335' } +1ms
  rtsp-relay:2:ConsumerServer ::ffff:192.168.1.102:55062 request: SETUP +1ms
  rtsp-relay:2:ClientWrapper 19922590415106746217863200177150217168134 - constructed +3ms
  rtsp-relay:2:Mounts 4996 rtp ports remaining +2ms
  rtsp-relay:2:ClientWrapper 19922590415106746217863200177150217168134 new client 1691454079170117820715723871222001183026 +0ms
  rtsp-relay:2:ConsumerServer Error setting up client TypeError: Cannot read properties of undefined (reading 'mount')
    at Client.setup (/usr/lib/node_modules/@warren-bank/rtsp-relay/lib/rtsp-streaming-server/lib/Client.js:76:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConsumerServer.setupRequest (/usr/lib/node_modules/@warren-bank/rtsp-relay/lib/rtsp-streaming-server/lib/ConsumerServer.js:136:7) +3ms
  rtsp-stream start-line sent RTSP/1.0 500 Internal Server Error +1ms
  rtsp-stream headers sent { CSeq: '0', Date: 'Sun, 04 Jun 2023 06:00:13 GMT' } +1ms
  rtsp-server socket connection ended +7ms
  rtsp-server socket connection closed +2ms
```

**Comment by warren-bank** [comment]
I had no problem playing my webcam's video stream through the relay..
did you try changing from `-c:v copy` to `-c:v mpeg1video`?

And, to be super explicit..
your video client (ex: vlc) is connecting to the consumer port of your relay?
ie: `rtsp://192.168.1.103:8554/stream1`

**Comment by adminy** [comment]
yep I did that, does it have to be mpeg1video?

I was wondering if h264 can be used.

**Comment by adminy** [comment]
never mind, it seems like ffplay works, vlc probably does something that makes it not work ...

**Comment by adminy** [comment]
```

  rtsp-stream decoding chunk 'OPTIONS rtsp://127.0.0.1:8554/stream1 RTSP/1.0\r\n' +
  'CSeq: 11\r\n' +
  'User-Agent: Lavf59.27.100\r\n' +
  'Session: 32901481207615670571881756641996240188\r\n' +
  '\r\n' +5s
  rtsp-stream start of header +1ms
  rtsp-stream end of header +0ms
  rtsp-server OPTIONS rtsp://127.0.0.1:8554/stream1 {
  cseq: '11',
  'user-agent': 'Lavf59.27.100',
  session: '32901481207615670571881756641996240188'
} +0ms
  rtsp-relay:2:ConsumerServer ::ffff:127.0.0.1:55420 request: OPTIONS +1ms
  rtsp-stream start-line sent RTSP/1.0 200 OK +1ms
  rtsp-stream headers sent {
  CSeq: '11',
  Date: 'Sun, 04 Jun 2023 07:00:59 GMT',
  OPTIONS: 'DESCRIBE SETUP PLAY STOP'
} +0ms
  rtsp-stream decoding chunk 'OPTIONS rtsp://127.0.0.1:8554/stream1 RTSP/1.0\r\n' +
  'CSeq: 11\r\n' +
  'User-Agent: Lavf59.27.100\r\n' +
  'Session: 2031682551603813979183145184872511381782\r\n' +
  '\r\n' +174ms
  rtsp-stream start of header +0ms
  rtsp-stream end of header +1ms
  rtsp-server OPTIONS rtsp://127.0.0.1:8554/stream1 {
  cseq: '11',
  'user-agent': 'Lavf59.27.100',
  session: '2031682551603813979183145184872511381782'
} +1ms
  rtsp-relay:2:ConsumerServer ::ffff:127.0.0.1:55436 request: OPTIONS +1ms
  rtsp-stream start-line sent RTSP/1.0 200 OK +1ms
  rtsp-stream headers sent {
  CSeq: '11',
  Date: 'Sun, 04 Jun 2023 07:00:59 GMT',
  OPTIONS: 'DESCRIBE SETUP PLAY STOP'
} +2ms
  rtsp-stream decoding chunk 'OPTIONS rtsp://127.0.0.1:8554/stream1 RTSP/1.0\r\n' +
  'CSeq: 11\r\n' +
  'User-Agent: Lavf59.27.100\r\n' +
  'Session: 109115606417412170141521559924525411010223\r\n' +
  '\r\n' +305ms
  rtsp-stream start of header +0ms
  rtsp-stream end of header +0ms
  rtsp-server OPTIONS rtsp://127.0.0.1:8554/stream1 {
  cseq: '11',
  'user-agent': 'Lavf59.27.100',
  session: '109115606417412170141521559924525411010223'
} +1ms
  rtsp-relay:2:ConsumerServer ::ffff:127.0.0.1:55438 request: OPTIONS +1ms
  rtsp-stream start-line sent RTSP/1.0 200 OK +1ms
  rtsp-stream headers sent {
  CSeq: '11',
  Date: 'Sun, 04 Jun 2023 07:00:59 GMT',
  OPTIONS: 'DESCRIBE SETUP PLAY STOP'
} +1ms

```

Is the stop command implemented?

**Comment by warren-bank** [comment]
> Is the stop command implemented?

honestly, I wrote this so long ago..
I don't remember anything.. at all.. about its internals;
I'd need to read the source to answer that.. same as anybody else.

**Comment by adminy** [comment]
Thanks anyways, my initial issue was solved. Have a lovely day.

**Comment by warren-bank** [comment]
[here](https://github.com/warren-bank/node-rtsp-relay/blob/v1.0.2/lib/rtsp-streaming-server/lib/ConsumerServer.js#L20-L29) is the list of RTSP request methods that are implemented by the server that interacts with the consumers.

[here](https://github.com/warren-bank/node-rtsp-relay/blob/v1.0.2/lib/rtsp-streaming-server/lib/ProducerServer.js#L16-L25) is the list of RTSP request methods that are implemented by the server that interacts with the producers.

**Comment by adminy** [comment]
yep, seems to be missing stop.
I can avoid rtsp entirely in my case if I refactor some code, so I'll go with that approach.

**Comment by warren-bank** [comment]
I'm no expert.. so I just referred to the spec:
* [RTSP v1](https://datatracker.ietf.org/doc/html/rfc2326#section-10)
* [RTSP v2](https://datatracker.ietf.org/doc/html/rfc7826#section-13)

"stop" isn't a documented method in either version.

most of the methods in both versions of the spec are implemented..
* v1 is all there
* v2 is mostly there

FWIW, the `TEARDOWN` method.. when sent by the client..
causes the consumer server to close its connection to the client..
which I assume is pretty equivalent to "stop".
